version: '3.8'

services:
  modem-sms-register:
    build: .
    container_name: modem-sms-register
    restart: unless-stopped
    
    # Device access for USB modem
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Adjust according to your modem device
    
    # Privileged mode for hardware access (use with caution)
    # privileged: true
    
    volumes:
      # Mount config file
      - ./config.json:/app/config.json:ro
      # Mount logs directory
      - ./logs:/app/logs
      # Optional: Mount additional config files
      - ./configs:/app/configs:ro
    
    environment:
      - CONFIG_PATH=/app/config.json
      - TZ=UTC
      - LOG_LEVEL=info
    
    # Network mode for direct hardware access
    network_mode: "host"
    
    # Alternative: Use bridge network if host network is not needed
    # ports:
    #   - "8080:8080"  # If you add HTTP endpoints later
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "modem-sms-register"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Labels for organization
    labels:
      - "com.example.service=modem-sms-register"
      - "com.example.version=1.0.0"

  # Optional: Add a monitoring service
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #   restart: unless-stopped

  # Optional: Add logging service
  # loki:
  #   image: grafana/loki:latest
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   restart: unless-stopped

# Optional: Create named volumes for persistent data
volumes:
  logs:
    driver: local
  configs:
    driver: local

# Optional: Create custom network
networks:
  modem-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16